CREATE DATABASE VENDAS;
CREATE TABLE PRODUTO (
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	SKU VARCHAR(30) NOT NULL,
	PRECOCUSTO NUMERIC(5,2),
	PRECOVENDA NUMERIC(5,2),
	TAMANHO CHAR (20),
	QUANTIDADE CHAR (20)
);